"""
Django settings for chesslens-core.

Generated by 'django-admin startproject' using Django 5.1.15.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-l7=acprxxmjza4_=pm=m-0__ae3@n=k%577_fo2$a@19-m%3-&",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Built-in UI for open-source users. Set to False in chesslens-cloud
# to disable the bundled frontend in favor of the production frontend.
CHESSLENS_ENABLE_UI = os.environ.get("CHESSLENS_ENABLE_UI", "True") == "True"


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "channels",
    # Local apps
    "chess_engine",
    "analysis",
    "explanation",
    "game",
    "api",
    "ws",
]

if CHESSLENS_ENABLE_UI:
    INSTALLED_APPS.append("ui")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if CHESSLENS_ENABLE_UI:
    MIDDLEWARE.append("ui.middleware.AnthropicKeyMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Django Channels — Redis channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379")],
        },
    },
}

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Redis cache (position evaluations, session state)
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379")

# Engine service
ENGINE_URL = os.environ.get("ENGINE_URL", None)  # None = local subprocess


def _int_env(name: str, default: int | None) -> int | None:
    val = os.environ.get(name)
    if val is None or val == "":
        return default
    try:
        return int(val)
    except ValueError:
        return default


# Stockfish defaults — applied by API views to every analyze() call unless
# overridden per-request. Only the engine binary is user-selectable in the UI;
# everything else is tuned via env vars.
STOCKFISH_DEFAULT_NODES = _int_env("STOCKFISH_DEFAULT_NODES", 500_000)
STOCKFISH_DEFAULT_MULTIPV = _int_env("STOCKFISH_DEFAULT_MULTIPV", 3)
STOCKFISH_PV_LENGTH = _int_env("STOCKFISH_PV_LENGTH", None)
STOCKFISH_PV_END_NODES = _int_env("STOCKFISH_PV_END_NODES", None)
STOCKFISH_PLAYED_MOVE_NODES = _int_env("STOCKFISH_PLAYED_MOVE_NODES", None)
STOCKFISH_DEFAULT_ENGINE = os.environ.get("STOCKFISH_DEFAULT_ENGINE", "") or None
STOCKFISH_DIR = os.environ.get("STOCKFISH_DIR", "") or None

# Anthropic
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# CORS — allow React dev server
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
}
