# Generated by Django 5.1.15 on 2026-03-16 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField()),
                ('white_player', models.CharField(blank=True, max_length=128)),
                ('black_player', models.CharField(blank=True, max_length=128)),
                ('result', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('skill_level', models.CharField(default='intermediate', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=8)),
                ('move_san', models.CharField(max_length=16)),
                ('fen', models.TextField()),
                ('cp_loss', models.IntegerField(blank=True, null=True)),
                ('cp_loss_label', models.CharField(blank=True, max_length=16)),
                ('priority_tier', models.CharField(blank=True, max_length=16)),
                ('explanation', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='game.savedgame')),
            ],
            options={
                'ordering': ['move_number', 'color'],
                'unique_together': {('game', 'move_number', 'color')},
            },
        ),
    ]
